version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blogapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14ckz9mlmzmln"
s3_prefix = "blogapi"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

