AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blog

  Sample SAM Template for blog

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BlogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: blogid
          AttributeType: S
      KeySchema:
        - AttributeName: blogid
          KeyType: HASH
      TableName: blog
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  
  BlogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blog/
      Handler: app.app
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref BlogTable
      Events:
        test:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        Listblog:
          Type: Api
          Properties:
            Path: /blog
            Method: get
        Putblog:
          Type: Api
          Properties:
            Path: /blog
            Method: post
        Getblog:
          Type: Api
          Properties:
            Path: /blog/{id}/
            Method: get
        Patchblog:
          Type: Api
          Properties:
            Path: /blog/{id}/
            Method: patch
        Deleteblog:
          Type: Api
          Properties:
            Path: /blog/{id}/
            Method: delete



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BlogFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  BlogFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BlogFunction.Arn
  BlogFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BlogFunctionRole.Arn
